- name: DLS1 IOS CONFIG
  hosts: DLS1
  connection: network_cli
  gather_facts: no

  tasks:

    - name: SET HOSTNAME
      ios_config:
        commands:
          - hostname DLS1

    - name: SET PASSWORD
      ios_config:
        commands:
          - enable secret cisco

    - name: SET USERNAME
      ios_config:
        commands:
          - username admin secret cisco123

    - name: ENCRYPT PLAIN TEXT
      ios_config:
        commands:
          - service password-encryption

    - name: SET BANNER
      ios_config:
        commands:
          - banner motd ^Authorized Access Only!!!^

    - name: CONFIGURE LINE VTY
      ios_config:
        parents:
          - line vty 0 4
        commands:
          - password cisco123
          - login local
          - transport input ssh

    - name: SET DOMAIN NAME
      ios_config:
        commands:
          - no ip domain-lookup
          - ip domain-name cisco.com
          - username admin secret cisco

    - name: GENERATE CRYPTO KEY
      ios_config:
        commands:
          - crypto key generate rsa usage-keys label ssh-key modulus 1024

    - name: Enable IP Routing
      ios_config:
        commands:
          - ip routing

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 10
        commands:
          - name CORE

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 20
        commands:
          - name MGMT

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 30
        commands:
          - name COMPUTE

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 99
        commands:
          - name NATIVE

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 100
        commands:
          - name R&D

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 200
        commands:
          - name EMPLOYEE

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 300
        commands:
          - name GUEST

    - name: SET VLAN Names
      ios_config:
        parents:
          - vlan 999
        commands:
          - name BLACKHOLE

    - name: CONFIGURE VTP
      ios_config:  
        command:
          - vtp mode server
          - vtp domain BRANCH_NYC
          - vtp version 2

    - name: CONFIGURE STP
      ios_config:
        commands:
          - spanning-tree mode pvst
          - spanning-tree vlan 10,20,30,100,200,300 priority 24576

    - name: CONFIGURE TRUNK AND NATIVE VLAN INTERFACE
      ios_config:
        parents: 
          - interface FastEthernet0/1
        commands: 
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: CONFIGURE TRUNK INTERFACES 
      ios_config:
        parents:
          - interface range FastEthernet0/2-3
        commands:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: CONFIGURE TRUNK AND NATIVE VLAN INTERFACES
      ios_config:
        parents:
          - interface range FastEthernet0/5-6
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk 
          - no shutdown

    - name: APPLY POLICY TO INBOUND TRAFFIC
      ios_config:
        parents:
          - interface FastEthernet0/5
        commands:
          - service-policy input VLAN30_POLICY
          - mls qos trust cos

    - name: CONFIGURE GIGABIT INTERFACE
      ios_config:
        parents:
          - interface GigabitEthernet0/1
        commands:
          - no switchport
          - ip address 172.16.12.225 255.255.255.252
          - duplex auto
          - speed auto
          - no shutdown

    - name: CONFIGURE GIGABIT INTERFACE
      ios_config:
        parents:
          - interface GigabitEthernet0/2
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown


    - name: CONFIGURE VLAN1
      ios_config:
        parents:
          - interface vlan1
        commands:
          - ip address 192.168.12.36 255.255.255.224

    - name: CONFIGURE VLAN10
      ios_config: 
        parents: 
          - interface vlan10
        commands:
          - ip address 172.16.12.1 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 priority 150
          - standby 1 preempt
          - no shutdown

    - name: CONFIGURE VLAN20
      ios_config:
        parents:
          - interface vlan20
        commands:
          - ip address 172.16.12.33 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 priority 150
          - standby 1 preempt
          - no shutdown

    - name: CONFIGURE VLAN30
      ios_config:
        parents:
          - interface vlan30
        commands:
          - ip address 172.16.12.65 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 priority 150
          - standby 1 preempt
          - service-policy output VLAN30_Policy
          - no shutdown

    - name: CONFIGURE VLAN99
      ios_config:
        parents:
          - interface vlan99
        commands:
          - ip address 172.16.12.97 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - standby 1 ip 172.16.12.254
          - standby 1 priority 150
          - standby 1 preempt
          - no shutdown

    - name: CONFIGURE VLAN100
      ios_config:
        parents:
          - interface vlan100
        commands:
          - ip address 172.16.12.129 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - no shutdown

    - name: CONFIGURE VLAN200 
      ios_config:
        parents:
          - interface vlan200
        commands:
          - ip address 172.16.12.161 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - no shutdown

    - name: CONFIGURE VLAN300
      ios_config:
        parents:
          - interface vlan300
        commands:
          - ip address 172.16.12.193 255.255.255.224
          - ip helper-address 172.16.12.226
          - ip nat inside
          - no shutdown

    - name: SHUTDOWN ALL UNUSED PORTS
      ios_config:
        parents:
          - interface FastEthernet0/4
        commands:
          - switchport access vlan 999
          - switchport mode access
          - shutdown

    - name: SHUTDOWN ALL UNUSED PORTS
      ios_config:
        parents:
          - interface range FastEthernet0/6-24
        commands:
          - switchport access vlan 999
          - switchport mode access
          - shutdown

    - name: CONFIGURE OSPF 
      ios_config:
        parents:
          - router ospf 1
        commands:
          - router-id 1.1.1.1
          - log-adjacency-changes
          - network 172.16.12.0 0.0.0.31 area 0
          - network 172.16.12.32 0.0.0.31 area 0
          - network 172.16.12.64 0.0.0.31 area 0
          - network 172.16.12.96 0.0.0.31 area 0
          - network 172.16.12.224 0.0.0.31 area 0
          - network 172.16.12.128 0.0.0.31 area 0
          - network 172.16.12.160 0.0.0.31 area 0
          - network 172.16.12.192 0.0.0.31 area 0

    - name: CONFIGURE RIP
      ios_config:
        parents:
          - router rip
        commands:
          - version 2
          - network 172.16.0.0
          - no auto-summary
    
    - name: ENABLE QOS
      ios_config:
        commands:
          - mls qos

    - name: CONFIGURE ACCESS-LIST
      ios_config:
        commands:
          - ip access-list extended VLAN30_ACL
          - permit ip 172.16.12.64 0.0.0.31 any

    - name: CONFIGURE QOS FOR VLAN 30 TRAFFIC PRIORITIZATION
      ios_config:
        commands:
          - class-map match-any VLAN30_CLASS
          - match access-group name VLAN30_ACL
          - policy-map VLAN30_POLICY
          - class VLAN30_CLASS
          - priority percent 50

    - name: SET DEFAULT GATEWAY
      ios_config:
        commands:
          - ip default-gateway 172.16.12.98
