- name: DLS2 IOS CONFIG
  hosts: DLS2
  connection: network_cli
  gather_facts: no

  tasks:

    - name: SET HOSTNAME
      ios_config:
        commands:
        - hostname DLS1

      - name: CONFIGURE PASSWORD
      ios_config:
        commands:
          - username admin secret cisco
          - enable secret dls2nyc

    - name: ENCRYPT PLAIN TEXT
      ios_config:
        commands:
          - service password-encryption

    - name: SET BANNER
      ios_config:
        commands:
          - banner motd ^Authorized Access Only!!!^

    - name: CONFIGURE LINE VTY
      ios_config:
        parents:
          - line vty 0 4
        commands:
          - password cisco123
          - login local
          - transport input ssh

    - name: GENERATE CRYPTO KEY
      ios_config:
        commands:
          - no ip domain-lookup
          - ip domain-name cisco.com
          - username admin secret cisco
          - crypto key generate rsa
          - 1024

    - name: Enable IP Routing
      ios_config:
        commands:
          - ip routing

    - name: CONFIGURE VTP
      ios_config:  
        command:
          - vtp mode client
          - vtp domain BRANCH_NYC
          - vtp version 2

    - name: Configure STP
      ios_config:
        commands:
          - spanning-tree mode pvst
          - spanning-tree vlan 10,20,30 priority 28672

    - name: CONFIGURE TRUNK AND NATIVE INTERFACE
      ios_config:
        parents:
          - interface FasterEthernet0/1
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk

    - name: CONFIGURE TRUNK INTERFACE
      ios_config:
        parents:
          - interface FastEthernet0/2
          - interface FastEthernet0/3
        commands:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk

    - name: CONFIGURE GIGABIT INTERFACE IP ADDRESS
      ios_config:
        parents:
          - interface GigabitEthernet0/1
        commands:
          - no switchport
          - ip address 172.16.12.230 255.255.255.252
          - duplex auto
          - speed auto

    - name: CONFIGURE GIGABIT INTERFACE
      ios_config:
        parents:
          - interface GigabitEthernet0/2
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk

    - name: CONFIGURE VLAN10
      ios_config:
        parents:
          - interface vlan10
        commands:
          - ip address 172.16.12.2 255.255.255.252
          - ip helper-address 172.16.12.229
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 preempt

    - name: CONFIGURE VLAN20
      ios_config:
        parents:
          - interface vlan20
        commands:
          - no ip address
          - ip helper-address 172.16.12.229
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 preempt

    - name: CONFIGURE OSPF
      ios_config:
        parents:
          - router ospf 1
        commands:
          - network 172.16.12.224 0.0.0.31 area 0

    - name: CONFIGURE RIP
      ios_config:
        parents:
          - router rip
        commands:
          - version 2
          - network 172.16.0.0
          - no auto-summary
