- name: R1 IOS CONFIG
  hosts: R1
  connection: network_cli
  gather_facts: no

  tasks:

    - name: SET HOSTNAME
      ios_config:
        commands:
          - hostname R1

    - name: CONFIGURE PASSWORD
      ios_config:
        commands:
          - username admin secret cisco
          - enable secret r1nyc

    - name: ENCRYPT PLAIN TEXT
      ios_config:
        commands:
          - service password-encryption

    - name: SET BANNER
      ios_config:
        commands:
          - banner motd ^Authorized Access Only!!!^

    - name: CONFIGURE LINE VTY
      ios_config:
        parents:
          - line vty 0 4
        commands:
          - password cisco123
          - login local
          - transport input ssh

    - name: GENERATE CRYPTO KEY
      ios_config:
        commands:
          - no ip domain-lookup
          - ip domain-name cisco.com
          - username admin secret cisco
          - crypto key generate rsa
          - 1024

    - name: CONFIGURE STP
      ios_config:
        commands:
          - spanning-tree mode pvst

    - name: CONFIGURE DHCP EXCLUDED ADDRESSES
      ios_config:
        commands:
          - ip dhcp excluded-address 172.16.12.1 172.16.12.10
          - ip dhcp excluded-address 172.16.12.33 172.16.12.43
          - ip dhcp excluded-address 172.16.12.65 172.16.12.75
          - ip dhcp excluded-address 172.16.12.97 172.16.12.107

    - name: Configure DHCP POOL FOR VLAN 10
      ios_config:
        commands:
          - ip dhcp pool vlan10
          - network 172.16.12.0 255.255.255.224
          - default-router 172.16.12.1

    - name: Configure DHCP Pool for VLAN 20
      ios_config:
        commands:
          - ip dhcp pool vlan20
          - network 172.16.12.32 255.255.255.224
          - default-router 172.16.12.33

    - name: Configure DHCP Pool for VLAN 30
      ios_config:
        commands:
          - ip dhcp pool vlan30
          - network 172.16.12.64 255.255.255.224
          - default-router 172.16.12.65

    - name: Configure DHCP Pool for VLAN 99
      ios_config:
        commands:
          - ip dhcp pool vlan99
          - network 172.16.12.96 255.255.255.224
          - default-router 172.16.12.97

    - name: CONFIGURE GIGABIT INTERFACE 
      ios_config:
        parents:
          - interface GigabitEthernet0/0
        commands:
          - ip address 172.16.12.226 255.255.255.252
          - duplex auto
          - speed auto

    - name: CONFIGURE GIGABIT INTERFACE 
      ios_config:
        parents:
          - interface GigabitEthernet0/1
        commands:
          - ip address 172.16.12.229 255.255.255.252
          - duplex auto
          - speed auto

    - name: CONFIGURE SERIAL INTERFACE
      ios_config:
        parents:
          - innterface serial0/0/0
        commands:
          - ip address 172.17.12.1 255.255.255.0
          - ip nat outside
          - clock rate 2000000

    - name: CONFIGURE OSPF
      ios_config:
        parents:
          - router ospf 1
        commands:
          - log-adjecency-changes
          - network 172.17.0.0 0.0.255.255 area 0

    - name: CONFIGURE RIP
      ios_config:
        parents:
          - router rip
        commands:
          - version 2
          - network 172.16.0.0
          - network 172.17.0.0
          - no auto-summary

    - name: CONFIGURE IP NAT
      ios_config:
        commands:
          - ip nat inside source list 1 interface Serial0/0/0 overload

    - name: CONFIGURE ACL
      ios_config:
        commands:
          - access-list 1 permit any


