- name: access-sw-01 IOS CONFIG
  hosts: access-sw-01
  connection: network_cli
  gather_facts: no

  tasks:

    - name: SET HOSTNAME
      ios_config:
        commands:
          - hostname access-sw-01

    - name: SET PASSWORD
      ios_config:
        commands:
          - enable secret {{ enable_secret }}

    - name: SET USERNAME
      ios_config:
        commands:
          - username admin secret {{ admin_secret }}

    - name: SET BANNER
      ios_config:
        commands:
          - ^Authorized Access Only!!!^

    - name: ENCRYPT PLAIN TEXT
      ios_config:
        commands:
          - service password-encryption  

    - name: CONFIGURE LINE VTY
      ios_config:
        parents:
          - line vty 0 4
        commands:
          - password {{ vty_password }}
          - login local
          - transport input ssh

    - name: SET DOMAIN NAME
      ios_config:
        commands:
          - no ip domain-lookup
          - ip domain-name cisco.com

    - name: GENERATE CRYPTO KEY
      ios_config:
        commands:
          - crypto key generate rsa usage-keys label ssh-key modulus 1024

    - name: CONFIGURE VTP
      ios_config:  
        command:
          - vtp mode client
          - vtp domain BRANCH_NYC
          - vtp version 2

    - name: CONFIGURE STP
      ios_config:
        command:
          - spanning-tree mode pvst

    - name: CONFIGURE TRUNK INTERFACE
      ios_config:
        parents:
          - interface FastEthernet0/1
        commands:
          - switchport trunk native vlan 99
          - switchport mode trunk

    - name: CONFIGURE INTERFACES
      ios_config:
        parents:
          - interface range FastEthernet0/2-5
        commands:
          - switchport mode access
          - switchport access vlan 20

    - name: CONFIGURE PORT SECURITY
      ios_config:
        parents:
          - interface range FastEthernet0/2-6
        commands:
          - switchport port-security
          - switchport port-security maximum 1
          - switchport port-security violation shutdown
          - switchport port-security mac-address sticky

    - name: CONFIGURE GIGABIT INTERFACE
      ios_config:
        parents:
          - interface GigabitEthernet0/1
        commands:
          - switchport trunk native vlan 99
          - switchport mode trunk

    - name: SHUTDOWN UNUSED GIGABIT INTERFACE
      ios_config:
        parents:
          - interface GigabitEthernet0/2
        commands:
          - switchport mode access
          - switchport access vlan 999
          - shutdown

    - name: SHUTDOWN UNUSED PORTS
      ios_config:
        parents:
          - interface range FastEthernet0/6-24
        commands:
          - switchport mode access
          - switchport access vlan 999
          - shutdown

    - name: CONFIGURE VLAN1
      ios_config:
        parents:
          - interface vlan1
        commands:
          - ip address 192.168.12.38 255.255.255.224

    - name: SET DEFAULT GATEWAY
      ios_config:
        commands:
          - ip default-gateway 172.16.12.98