- name: l3-sw-02 IOS CONFIG
  hosts: l3-sw-02
  connection: network_cli
  gather_facts: no

  tasks:

    - name: SET HOSTNAME
      ios_config:
        commands:
          - hostname l3-sw-02

    - name: SET PASSWORD
      ios_config:
        commands:
          - enable secret {{ enable_secret }}

    - name: SET USERNAME
      ios_config:
        commands:
          - username admin secret {{ admin_secret }}

    - name: ENCRYPT PLAIN TEXT
      ios_config:
        commands:
          - service password-encryption

    - name: SET BANNER
      ios_config:
        commands:
          - banner motd ^Authorized Access Only!!!^

    - name: CONFIGURE LINE VTY
      ios_config:
        parents:
          - line vty 0 4
        commands:
          - password {{ vty_password }}
          - login local
          - transport input ssh

    - name: SET DOMAIN NAME
      ios_config:
        commands:
          - no ip domain-lookup
          - ip domain-name cisco.com

    - name: GENERATE CRYPTO KEY
      ios_config:
        commands:
          - crypto key generate rsa usage-keys label ssh-key modulus 1024

    - name: Enable IP Routing
      ios_config:
        commands:
          - ip routing

    - name: CONFIGURE VLANs 
      ios_config:
        parents: "vlan {{ item.id }}"
        commands:
          - name {{ item.name }}
      loop:
        - { id: 10, name: "CORE" }
        - { id: 20, name: "MGMT" }
        - { id: 30, name: "COMPUTE" }
        - { id: 99, name: "NATIVE" }
        - { id: 100, name: "R&D" }
        - { id: 200, name: "EMPLOYEE" }
        - { id: 300, name: "GUEST" }
        - { id: 999, name: "BLACKHOLE" }

    - name: CONFIGURE VTP
      ios_config:  
        command:
          - vtp mode client
          - vtp domain BRANCH_NYC
          - vtp version 2

    - name: Configure STP
      ios_config:
        commands:
          - spanning-tree mode pvst
          - spanning-tree vlan 10,20,30,100,200,300 priority 28672

    - name: CONFIGURE TRUNK AND NATIVE VLAN INTERFACE
      ios_config:
        parents:
          - interface FasterEthernet0/1
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: CONFIGURE TRUNK INTERFACE
      ios_config:
        parents:
          - interface range FastEthernet0/2-3
        commands:
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: CONFIGURE TRUNK AND NATIVE VLAN INTERFACE
      ios_config:
        parents:
          - interface range FastEthernet0/4-5
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: CONFIGURE GIGABIT INTERFACE IP ADDRESS
      ios_config:
        parents:
          - interface GigabitEthernet0/1
        commands:
          - no switchport
          - ip address 172.16.12.230 255.255.255.252
          - duplex auto
          - speed auto
          - no shutdown

    - name: CONFIGURE GIGABIT INTERFACE
      ios_config:
        parents:
          - interface GigabitEthernet0/2
        commands:
          - switchport trunk native vlan 99
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - no shutdown

    - name: CONFIGURE VLAN1
      ios_config:
        parents:
          - interface vlan1
        commands:
          - ip address 192.168.12.37 255.255.255.224
          - no shutdown

    - name: CONFIGURE VLAN10
      ios_config:
        parents:
          - interface vlan10
        commands:
          - ip address 172.16.12.2 255.255.255.224
          - ip helper-address 172.16.12.229
          - ip nat inside
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 preempt

    - name: CONFIGURE VLAN20
      ios_config:
        parents:
          - interface vlan20
        commands:
          - ip address 172.16.12.34 255.255.255.224
          - ip helper-address 172.16.12.229
          - ip nat inside
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 preempt

    - name: CONFIGURE VLAN30
      ios_config:
        parents:
          - interface vlan30
        commands:
          - ip address 172.16.12.66 255.255.255.224
          - ip helper-address 172.16.12.229
          - ip nat inside
          - standby version 2
          - standby 1 ip 172.16.12.254
          - standby 1 preempt

    - name: CONFIGURE OSPF
      ios_config:
        parents:
          - router ospf 1
        commands:
          - router-id 3.3.3.3
          - log-adjacency-changes
          - network 172.16.12.224 0.0.0.31 area 0
          - network 172.16.12.0 0.0.0.31 area 0
          - network 172.16.12.32 0.0.0.31 area 0
          - network 172.16.12.64 0.0.0.31 area 0
          - network 172.16.12.96 0.0.0.31 area 0
          - network 172.16.12.128 0.0.0.31 area 0
          - network 172.16.12.160 0.0.0.31 area 0
          - network 172.16.12.192 0.0.0.31 area 0

    - name: CONFIGURE RIP
      ios_config:
        parents:
          - router rip
        commands:
          - version 2
          - network 172.16.0.0
          - no auto-summary

    - name: ENABLE QOS
      ios_config:
        commands:
          - mls qos

    - name: CONFIGURE ACCESS-LIST
      ios_config:
        commands:
          - ip access-list extended VLAN30_ACL
          - permit ip 172.16.12.64 0.0.0.31 any

    - name: CONFIGURE QOS FOR VLAN 30 TRAFFIC PRIORITIZATION
      ios_config:
        commands:
          - class-map match-any VLAN30_CLASS
          - match access-group name VLAN30_ACL
          - policy-map VLAN30_POLICY
          - class VLAN30_CLASS
          - priority percent 50

    - name: SET DEFAULT GATEWAY
      ios_config:
        commands:
          - ip default-gateway 172.16.12.98